# Generated by Django 3.2.16 on 2022-10-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = False

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300)),
                ('autor', models.CharField(max_length=100)),
                ('precio', models.CharField(max_length=30)),
            ],
        ),
    ]
